#!/usr/bin/env python3
"""
Regenerate README.md from the frontmatter in every solutions/*/notes.md.

Run it yourself:      python scripts/build_index.py
Or let the GitHub Action run it on every push.

Each notes.md starts with a YAML-ish block between --- lines. We parse it by
hand so there are no dependencies to install.
"""

from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOLUTIONS = ROOT / "solutions"
README = ROOT / "README.md"

FIELDS = (
    "number",
    "title",
    "difficulty",
    "pattern",
    "date_solved",
    "stage_needed",
    "video",
    "review_next",
)


def parse_frontmatter(path: Path) -> dict:
    """Pull the key: value block between the first two --- lines."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}

    _, block, _ = text.split("---", 2)
    data = {}
    for line in block.strip().splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        data[key.strip()] = value.strip()
    return data


def collect() -> list[dict]:
    entries = []
    for notes in sorted(SOLUTIONS.glob("*/notes.md")):
        meta = parse_frontmatter(notes)
        if not meta.get("number"):
            continue
        meta["folder"] = notes.parent.name
        entries.append(meta)

    entries.sort(key=lambda m: int(m.get("number", 0)))
    return entries


def build_table(entries: list[dict]) -> str:
    lines = [
        "| # | Problem | Difficulty | Pattern | Solved | Video |",
        "|---|---------|------------|---------|--------|-------|",
    ]
    for e in entries:
        link = f"[{e.get('title', '?')}](solutions/{e['folder']}/notes.md)"
        video = e.get("video", "none")
        video = "" if video in ("none", "", "no") else f"[watch]({video})"
        lines.append(
            f"| {e.get('number')} | {link} | {e.get('difficulty', '')} | "
            f"{e.get('pattern', '')} | {e.get('date_solved', '')} | {video} |"
        )
    return "\n".join(lines)


def build_pattern_counts(entries: list[dict]) -> str:
    counts: dict[str, int] = {}
    for e in entries:
        pattern = e.get("pattern", "unsorted")
        counts[pattern] = counts.get(pattern, 0) + 1

    lines = ["| Pattern | Problems solved |", "|---------|-----------------|"]
    for pattern, n in sorted(counts.items(), key=lambda kv: -kv[1]):
        lines.append(f"| {pattern} | {n} |")
    return "\n".join(lines)


def build_review_queue(entries: list[dict]) -> str:
    today = date.today().isoformat()
    due = [e for e in entries if e.get("review_next", "9999") <= today]
    if not due:
        return "_Nothing due. Solve something new._"

    lines = ["| # | Problem | Pattern | Was due |", "|---|---------|---------|---------|"]
    for e in sorted(due, key=lambda x: x.get("review_next", "")):
        link = f"[{e.get('title', '?')}](solutions/{e['folder']}/notes.md)"
        lines.append(
            f"| {e.get('number')} | {link} | {e.get('pattern', '')} | "
            f"{e.get('review_next', '')} |"
        )
    return "\n".join(lines)


def main() -> None:
    entries = collect()

    readme = f"""# LeetCode in Python — learning in public

Solutions, and more importantly **notes**, from working through LeetCode in
Python. Each problem gets a folder with the code and a write-up: the insight in
one sentence, how I could have derived it, where I got stuck, and the mistake I
made.

I'm also turning these into videos for people learning DSA from scratch, so the
explanations are written to survive being repeated by someone who just learned
them.

**{len(entries)} problems solved.**

---

## Review queue — due today

Cold re-solves, no notes, from scratch. If it fails, the interval resets.

{build_review_queue(entries)}

---

## All problems

{build_table(entries)}

---

## Patterns

The goal is mastering ~20 patterns, not counting problems.

{build_pattern_counts(entries)}

---

## Repo layout

```
solutions/0015-3sum/
    solution.py     # my code, with the reasoning in comments
    notes.md        # the actual learning artifact
_template/          # copy this to start a new problem
scripts/            # build_index.py regenerates this README
```

## How I work

1. 25 minutes alone. No AI, no editorial. Write pseudocode even if the Python won't come.
2. Escalate through hints only as needed. Full walkthroughs are a last resort.
3. Write the notes immediately, while it's warm.
4. Re-solve cold on a spaced schedule: 1, 3, 7, 14, 30 days.
5. Record the video only after a clean cold re-solve.

---

_README generated by `scripts/build_index.py` — edit the notes, not this file._
"""

    README.write_text(readme, encoding="utf-8")
    print(f"Wrote README.md with {len(entries)} problems.")


if __name__ == "__main__":
    main()
